"""add_signalwire_provider

Revision ID: 17a225bcbeb7
Revises: b20220ac7423
Create Date: 2026-05-25 19:36:57.470411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17a225bcbeb7'
down_revision: Union[str, None] = 'b20220ac7423'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
