"""add_lead_notes_followup_address

Revision ID: 8bcdb30945ab
Revises: 17a225bcbeb7
Create Date: 2026-05-26 03:59:16.004172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8bcdb30945ab'
down_revision: Union[str, None] = '17a225bcbeb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('leads', sa.Column('follow_up_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('leads', sa.Column('address', sa.String(), nullable=True))
    op.add_column('leads', sa.Column('city', sa.String(), nullable=True))
    op.add_column('leads', sa.Column('state', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leads', 'state')
    op.drop_column('leads', 'city')
    op.drop_column('leads', 'address')
    op.drop_column('leads', 'follow_up_at')
    op.drop_column('leads', 'notes')
    # ### end Alembic commands ###
