"""add_social_posts_social_leads

Revision ID: 91a0435fc938
Revises: 8bcdb30945ab
Create Date: 2026-05-26 05:32:08.165367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91a0435fc938'
down_revision: Union[str, None] = '8bcdb30945ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
